name: 'Trybe Image Builder'
author: 'Trybe'
description: 'Esta GitHub Action permite realizar build de imagens obtendo variáveis de ambiente como argumentos de build.'
inputs:
  imageTag:
    description: 'Tag a ser utilizada antes de enviar para o ECR.'
    required: true
  prefix:
    description: 'Prefixo nas variáveis para observar e incluir durante a construção da imagem.'
    required: false
    default: 'BUILD_ENV_'
  dockerfile:
    description: 'Caminho para o arquivo Dockerfile.'
    required: false
    default: 'Dockerfile'

runs:
  using: 'composite'
  steps:
    - id: job
      shell: bash
      run: ${{ github.action_path }}/build.sh
      env:
        PREFIX: ${{ inputs.prefix }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        TAG: ${{ inputs.imageTag }}
